blank_issues_enabled: false
contact_links:
  - name: 📬 Soporte TI SLEP Colchagua
    url: mailto:soporte.ti@slepcolchagua.cl
    about: Contacta al equipo de tecnología si tienes dudas o necesitas acceso.
